### ISSUE TITLE
problem about view size

### ISSUE THREAD

**Issue by gnastnosaj** [iammert/InteractivePlayerView#1]
sample not display well on tablet，set durationSize may works, but still some problem, the progress point  is too large

**Comment by gnastnosaj** [comment]
test on nexus10 android l

**Comment by iammert** [comment]
I fixed that issue. Hope it is fine now. Can you check and give feedback about it now. @gnastnosaj 
Thanks.

**Comment by gnastnosaj** [comment]
:) it is fine now
