### ISSUE TITLE
setCoverDrawable and API level <= 21

### ISSUE THREAD

**Issue by DubiousCactus** [iammert/InteractivePlayerView#5]
Hi ! 
There is an error on the "getDrawable" call in your method "setCoverDrawable". I fixed it on my fork by adding "getResources" right before "getDrawable", but it looks like the fix doesn't take effect ... Could you fix it on your repo ?

Thanks !

Théo

**Comment by DubiousCactus** [comment]
Okay I fixed it on my repo and used it with JitPack, but I don't know if I can fix it on yours, just letting you know ;) 
And thanks a lot for this awesome work !

**Comment by iammert** [comment]
I will be happy if you send me PR about this! Thanks.

**Comment by DubiousCactus** [comment]
Done ! :)

**Comment by iammert** [comment]
I merged your PR. Thanks for contribution:)
